swagger: "2.0"
info:
  version: "1.0.0"
  title: "Swagger Bookstore"
  description: "A sample API that uses a bookstore as an example to demonstrate features in the swagger-2.0 specification"
basePath: "/v1"
paths:
  /books:
    get:
      description: "Returns all books from the system that the user has access to"
      produces:
        - "application/json"
      responses:
        "200":
          description: "A list of books."
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Book"
definitions:
  Book:
    type: "object"
    required:
      - "id"
      - "name"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
      tag:
        type: "string"
